import json
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class ReleaseToolTests(unittest.TestCase):
    def run_tool(self, name, *args):
        proc = subprocess.run([sys.executable, str(ROOT / "tools" / name), *args], capture_output=True, text=True, cwd=ROOT)
        return proc.returncode, json.loads(proc.stdout)

    def test_private_scan_is_clean(self):
        code, report = self.run_tool("private_scan.py")
        self.assertEqual(code, 0, json.dumps(report.get("hits"), indent=1))

    def test_release_check_agrees_on_version(self):
        code, report = self.run_tool("release_check.py")
        self.assertEqual(code, 0, report.get("problems"))
        code, report = self.run_tool("release_check.py", "--tag", report["expected_tag"])
        self.assertEqual(code, 0, report.get("problems"))
        code, report = self.run_tool("release_check.py", "--tag", "v9.9.9")
        self.assertEqual(code, 1)


class GeneratedDocsTests(unittest.TestCase):
    def test_backends_page_is_current(self):
        # docs/BACKENDS.md is generated; a stale copy would misname what a route runs.
        proc = subprocess.run([sys.executable, str(ROOT / "tools" / "backends_doc.py"), "--check"],
                              capture_output=True, text=True, cwd=ROOT)
        self.assertEqual(proc.returncode, 0, proc.stderr or proc.stdout)
        text = (ROOT / "docs" / "BACKENDS.md").read_text(encoding="utf-8")
        self.assertIn("Generated by tools/backends_doc.py", text)
        for program in ("OpenAssetTools", "gsc-tool", "FFmpeg", "Blender", "Cast", "CoDLuaDecompiler", "Greyhound", "Husky", "C2M"):
            self.assertIn(program, text, program)


class RepositoryHygieneTests(unittest.TestCase):
    """Native-run findings: the documented procedure must not dirty or leak into the tree."""

    def test_documented_qualify_home_is_ignored_by_git(self):
        # docs/WINDOWS-QUALIFICATION.md sets PAT_HOME to <repo>/.qualify-home, and `configure`
        # writes the user's absolute storage path into its config.json. If git does not ignore
        # that directory, private_scan.py (which lists untracked files too) flags it.
        proc = subprocess.run(["git", "check-ignore", "-q", ".qualify-home/config.json"], cwd=ROOT)
        self.assertEqual(proc.returncode, 0, ".qualify-home/ must be ignored by git")

    def test_no_generated_egg_info_is_tracked(self):
        # `pip install -e .` regenerates *.egg-info; tracking it makes every install dirty the tree.
        out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
        self.assertEqual([line for line in out.splitlines() if ".egg-info" in line], [])


if __name__ == "__main__":
    unittest.main()
