"""The track record page is generated from docs/track-record.json and is the first thing README
points at; these checks keep the page, the data and the framing of SUPPORT.md from drifting."""
import json
import re
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


class TrackRecordDataTests(unittest.TestCase):
    def setUp(self):
        self.data = json.loads(read("docs/track-record.json"))

    def test_data_shape_and_internal_consistency(self):
        d = self.data
        self.assertEqual(d["schema"], 1)
        self.assertEqual(d["totals"]["entries"], sum(c["entries"] for c in d["categories"]))
        self.assertEqual(d["totals"]["accepted"], sum(c["accepted"] for c in d["categories"]))
        for c in d["categories"]:
            self.assertEqual(c["entries"], sum(c["by_status"].values()), c["category"])
            self.assertEqual(c["accepted"], sum(v for k, v in c["by_status"].items() if k.startswith("accepted")))
            for status in c["by_status"]:
                self.assertIn(status, d["status_definitions"], status)
        categories = {c["category"] for c in d["categories"]}
        for m in d["milestones"]:
            self.assertIn(m["category"], categories, m["id"])
            self.assertRegex(m["accepted_on"], r"^\d{4}-\d{2}-\d{2}$")
            self.assertEqual(set(m), {"id", "title", "category", "accepted_on", "base", "map", "how", "scope", "quote"})
        for c in d["crossings"]:
            self.assertEqual(set(c), {"id", "title", "packaged_route", "what_happened", "reproducible_from"})
        self.assertGreaterEqual(len(d["milestones"]), 6)
        self.assertGreaterEqual(len(d["crossings"]), 3)
        self.assertEqual(len(d["workflow"]), 4)

    def test_data_carries_no_private_material(self):
        text = read("docs/track-record.json")
        for pattern in (r"/home/", r"\.local/", r"\b[0-9a-f]{64}\b", r"halo-(modding|plutonium)-dev",
                        r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b"):
            self.assertIsNone(re.search(pattern, text), pattern)


class TrackRecordPageTests(unittest.TestCase):
    def test_rendered_page_matches_generator(self):
        proc = subprocess.run([sys.executable, str(ROOT / "tools" / "track_record_doc.py"), "--check"],
                              capture_output=True, text=True, cwd=ROOT)
        self.assertEqual(proc.returncode, 0, (proc.stderr or proc.stdout) + "\nrun: python tools/track_record_doc.py --write")
        self.assertIn("Generated by tools/track_record_doc.py", read("docs/TRACK-RECORD.md"))

    def test_page_states_totals_scope_milestones_and_crossings(self):
        d = json.loads(read("docs/track-record.json"))
        text = read("docs/TRACK-RECORD.md")
        self.assertIn(f"{d['totals']['accepted']} of {d['totals']['entries']}", text)
        self.assertIn(d["scope_note"], text)
        for m in d["milestones"]:
            self.assertIn(m["title"], text)
            self.assertIn(m["scope"], text)
        for c in d["crossings"]:
            self.assertIn(c["title"], text)
        for status, definition in d["status_definitions"].items():
            self.assertIn(f"`{status}`", text)


class FramingTests(unittest.TestCase):
    def test_readme_leads_with_the_record_before_status(self):
        text = read("README.md")
        self.assertIn("docs/TRACK-RECORD.md", text)
        self.assertLess(text.index("docs/TRACK-RECORD.md"), text.index("> **Status"))

    def test_support_scopes_the_matrix_to_packaged_routes(self):
        text = read("docs/SUPPORT.md")
        self.assertRegex(text, r"(?m)^# Packaged route qualification for `")
        self.assertIn("not a ceiling", text)
        self.assertIn("TRACK-RECORD.md", text)
        self.assertIn("## Beyond the packaged routes", text)

    def test_every_unpackaged_item_names_the_agent_path(self):
        text = read("docs/SUPPORT.md")
        section = text.split("## Beyond the packaged routes", 1)[1].split("## Release bars", 1)[0]
        bullets = []
        for line in section.splitlines():
            if line.startswith("- "):
                bullets.append(line)
            elif line.startswith("  ") and bullets:
                bullets[-1] += " " + line.strip()
        self.assertGreaterEqual(len(bullets), 5)
        for line in bullets:
            self.assertRegex(line, r"agent|TRACK-RECORD|playbook|FOR-AGENTS", line)

    def test_glossary_and_entry_points_name_the_record(self):
        context = read("CONTEXT.md")
        self.assertIn("**Packaged route**", context)
        self.assertIn("**Track record**", context)
        for doc in ("AGENTS.md", "docs/FOR-AGENTS.md", "skills/plutonium-agent-toolkit/SKILL.md"):
            self.assertIn("TRACK-RECORD.md", read(doc), doc)
        self.assertIn("## What worked", read("docs/history/README.md"))


if __name__ == "__main__":
    unittest.main()
