"""``module changelog``: what changed in one module, and why, from bytes that already exist.

A person who opens a module on a repository should be able to read its history without a build,
a receipt or an agent. This route writes that page and nothing else: one ``CHANGELOG.md`` beside
``module.json``, generated from the module's own git history and its evidence ledger, grouped by
the version each commit's declaration carried.

Three sources, all read-only, none of them new:

* ``git log`` over the module directory, bounded and never raising. No git, no repository and no
  readable history are not defects in the module: they are one paragraph saying the history could
  not be read, with the reason.
* the ``evidence.json`` beside the declaration, for the row types that say what a person saw:
  ``known-issue``, ``game-tested`` and ``player-accepted``. A module with no ledger simply has no
  such lines.
* the declaration's current ``version``, which is the section a reader lands on first even when no
  commit carries it yet.

The file is generated and never hand-edited: ``module verify-declaration`` regenerates it and
reports the difference, and ``--check`` exits 1 when the file on disk is not what this renders.
Determinism is the whole contract -- the same directory at the same commit renders the same bytes,
so a diff is a change in the module and never a change in the clock.
"""
from __future__ import annotations

import difflib
import hashlib
import json
import os
import shutil
import stat
import subprocess
from pathlib import Path

from ..core.errors import INPUT_INVALID, INPUT_LIMIT, INPUT_MISSING, OPERATION_FAILED, Failure
from . import ledger

PROTOCOL = "pat.module-changelog/1"
FILENAME = "CHANGELOG.md"

GIT_TIMEOUT = 20
# The history is bounded so a module in a repository with a long past renders in a known time.
MAX_COMMITS = 2000
MAX_DECLARATION_BYTES = 256 * 1024
SHORT = 8

# The section commits older than the declaration land in: they are the module's history, and the
# version they were written under is a thing the repository does not record.
UNVERSIONED = "unversioned"
GENERATED = "Generated by pat module changelog from git history and evidence.json; do not edit by hand."
# The ledger rows that say what somebody saw. A lineage, an authored or a built-alone row is
# provenance, not a change a reader of this page is looking for.
ROW_TYPES = ("known-issue", "game-tested", "player-accepted")


# ----- reading -----------------------------------------------------------------------------

def _git(directory: Path, args: list[str]) -> bytes | None:
    """One bounded ``git`` run, captured, never raising: None when git fails, times out or is not
    there. Nothing here writes to or fetches into the repository."""
    try:
        done = subprocess.run(["git", "-C", str(directory), *args], capture_output=True, timeout=GIT_TIMEOUT)
    except (OSError, ValueError, subprocess.SubprocessError):
        return None
    return done.stdout if done.returncode == 0 else None


def _git_text(directory: Path, args: list[str]) -> str | None:
    out = _git(directory, args)
    return None if out is None else out.decode("utf-8", errors="replace")


def declaration(directory: Path) -> dict:
    """The module's own declaration: the id this page is about and the version it is at now."""
    path = directory / "module.json"
    if path.is_symlink() or not path.is_file():
        raise Failure(INPUT_MISSING, f"No module.json in {directory}",
                      "module changelog reads one module directory: the folder holding module.json.")
    if path.stat().st_size > MAX_DECLARATION_BYTES:
        raise Failure(INPUT_LIMIT, f"module.json exceeds {MAX_DECLARATION_BYTES} bytes: {path}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        raise Failure(INPUT_INVALID, f"module.json is not readable JSON: {path} ({exc})", field="/") from exc
    if not isinstance(data, dict) or not isinstance(data.get("id"), str):
        raise Failure(INPUT_INVALID, f"module.json declares no id: {path}", field="/id")
    return data


def _history(directory: Path) -> tuple[list[dict] | None, str | None, str]:
    """Every commit that touched this directory, newest first, and the directory's path inside
    the repository. ``(None, reason, "")`` when the history could not be read at all."""
    if shutil.which("git") is None:
        return None, "git is not on this machine", ""
    prefix = _git_text(directory, ["rev-parse", "--show-prefix"])
    if prefix is None:
        return None, "the module directory is not inside a git repository", ""
    prefix = prefix.strip()
    out = _git_text(directory, ["log", f"--max-count={MAX_COMMITS}", "--follow",
                                "--format=%H%x00%ad%x00%s", "--date=short", "--", "."])
    if out is None:
        return None, "git could not read this directory's history", prefix
    commits = []
    for line in out.splitlines():
        sha, sep, rest = line.partition("\0")
        date, tab, subject = rest.partition("\0")
        if not sep or not tab or len(sha) != 40:
            continue
        commits.append({"sha": sha, "short": sha[:SHORT], "date": date, "subject": subject})
    return commits, None, prefix


def _versions(directory: Path, prefix: str, commits: list[dict]) -> None:
    """The version each commit's own declaration carried, read once per distinct declaration.

    Two thousand commits over a module whose ``module.json`` changed five times is five reads:
    ``rev-parse`` names the blob, and the blob is the cache key. A commit with no declaration for
    this directory predates it and carries no version at all.
    """
    seen: dict[str, str | None] = {}
    for row in commits:
        blob = (_git_text(directory, ["rev-parse", f"{row['sha']}:{prefix}module.json"]) or "").strip()
        if not blob:
            row["version"] = None
            continue
        if blob not in seen:
            raw = _git(directory, ["show", f"{row['sha']}:{prefix}module.json"])
            try:
                data = json.loads(raw.decode("utf-8")) if raw is not None else None
            except (UnicodeDecodeError, ValueError):
                data = None
            version = data.get("version") if isinstance(data, dict) else None
            seen[blob] = version if isinstance(version, str) and version else None
        row["version"] = seen[blob]


def _line(row: dict) -> str:
    """One ledger row as the line a reader sees. The shapes are fixed, so a row that was written
    once reads the same in every module's page."""
    maps = ", ".join(row["scope"]["maps"])
    at = row.get("at") or "undated"
    if row["type"] == "known-issue":
        closes = f" closed by {row['closes_with'][:SHORT]}" if row.get("closes_with") else ""
        return f"- known issue ({at}, {row['seen_by']}): {row['issue']}{closes}"
    if row["type"] == "game-tested":
        return f"- game-tested {row['result']} on {maps} ({at}, run {row['run']})"
    return f"- player-accepted {row['outcome']} on {maps} ({at})"


def _ledger_rows(directory: Path) -> tuple[list[dict], str]:
    """The ledger's seen-it rows, or none at all. A module with no ledger is not a defect here."""
    path = directory / ledger.FILENAME
    if path.is_symlink() or not path.is_file():
        return [], "absent"
    try:
        _raw, data = ledger.read(path)
    except Failure as exc:
        return [], f"unreadable: {exc.message[:200]}"
    book, _diagnostics = ledger.validate(data)
    rows = []
    for index, row in enumerate((book or {}).get("rows", [])):
        if row["type"] in ROW_TYPES:
            rows.append({"index": index, "type": row["type"], "at": row.get("at"), "text": _line(row)})
    return rows, "read"


# ----- grouping ----------------------------------------------------------------------------

def _sections(commits: list[dict], rows: list[dict], current: str | None) -> list[dict]:
    """The version sections, newest first, with the declaration's current version leading.

    A commit belongs to the version its own declaration carried, which is what makes the page
    honest: a fix that shipped in 0.1.0 stays under 0.1.0 after the bump. Ordering is the newest
    commit each version holds, so it never needs to parse a version string to decide which of two
    is later, and ``unversioned`` is always last because it is what came before all of them.
    """
    order: dict[str, int] = {}
    grouped: dict[str, list[dict]] = {}
    for position, commit in enumerate(commits):
        key = commit["version"] or UNVERSIONED
        grouped.setdefault(key, []).append(commit)
        order.setdefault(key, position)  # commits arrive newest first: the first seen is the newest
    keys = [key for key in grouped if key != UNVERSIONED]
    keys.sort(key=lambda key: (order[key], key))
    if current and current not in keys:
        keys.insert(0, current)
    elif current:
        keys.remove(current)
        keys.insert(0, current)
    if UNVERSIONED in grouped:
        keys.append(UNVERSIONED)

    sections = []
    for key in keys:
        found = grouped.get(key, [])
        # Newest first, and a day two commits share is broken by the sha, so the page is the same
        # bytes on every host and in every clone.
        listed = sorted(sorted(found, key=lambda c: c["sha"]), key=lambda c: c["date"], reverse=True)
        dates = [c["date"] for c in found]
        sections.append({"version": key, "current": key == current,
                         "first": min(dates) if dates else None, "last": max(dates) if dates else None,
                         "commits": [{k: c[k] for k in ("sha", "short", "date", "subject")} for c in listed],
                         "rows": []})

    # A row lands under every version whose commit dates span its `at`. A row with no date, and a
    # row dated outside every version's span, goes under the current version rather than nowhere:
    # a page that silently drops an issue somebody filed is worse than one that dates it loosely.
    placed: set[int] = set()
    for section in sections:
        if section["first"] is None:
            continue
        for row in rows:
            at = (row["at"] or "")[:10]
            if at and section["first"] <= at <= section["last"]:
                section["rows"].append(row)
                placed.add(row["index"])
    leftover = [row for row in rows if row["index"] not in placed]
    if leftover and sections:
        home = next((s for s in sections if s["current"]), sections[0])
        home["rows"].extend(leftover)
    for section in sections:
        # Oldest first inside a section, and a row with no date after every dated one: it is the
        # row nothing can place in the version's span, so it reads last rather than first.
        section["rows"] = [{"index": r["index"], "type": r["type"], "at": r["at"], "text": r["text"]}
                           for r in sorted(section["rows"], key=lambda r: (r["at"] is None, r["at"] or "", r["index"]))]
    return sections


# ----- rendering ---------------------------------------------------------------------------

def _text(module_id: str, sections: list[dict], reason: str | None) -> str:
    lines = [f"# Changelog: {module_id}", "", GENERATED, ""]
    if reason is not None:
        lines.append(f"The history of this module could not be read ({reason}), so this page has no version "
                     "sections. Nothing is missing from the module: the page is generated from a repository, and "
                     "this directory is not one it can read. Run this route again from a clone with its history, "
                     "or read the module's evidence.json for what has been seen of it.")
        lines.append("")
        return "\n".join(lines)
    for section in sections:
        lines.append(f"## {section['version']}")
        lines.append("")
        body = [f"- {c['short']} {c['date']} {c['subject']}" for c in section["commits"]]
        body += [row["text"] for row in section["rows"]]
        lines += body or ["No commit and no evidence row under this version yet."]
        lines.append("")
    return "\n".join(lines)


def render(directory) -> dict:
    """The generated page, its version sections and what was read to build them."""
    directory = Path(directory).expanduser()
    metadata = declaration(directory)
    current = metadata.get("version") if isinstance(metadata.get("version"), str) else None
    commits, reason, prefix = _history(directory)
    rows, ledger_state = _ledger_rows(directory)
    sections: list[dict] = []
    if commits is not None:
        _versions(directory, prefix, commits)
        sections = _sections(commits, rows, current)
    inputs = {
        "module": metadata["id"], "version": current,
        "history": "not_counted" if commits is None else "read",
        "reason": reason,
        "commits": 0 if commits is None else len(commits),
        "truncated": commits is not None and len(commits) >= MAX_COMMITS,
        "ledger": ledger_state, "ledger_rows": len(rows),
    }
    return {"text": _text(metadata["id"], sections, reason), "versions": sections, "inputs": inputs}


# ----- writing and checking ------------------------------------------------------------------

def _regular(path: Path) -> bool:
    """Whether the page is already on disk here, refusing a path that is not a regular file.

    A module directory holding ``CHANGELOG.md -> ~/.bashrc`` must not make this route write
    through the link, and a FIFO in that name must not make it block forever on an open that never
    returns. One ``lstat`` decides; nothing opens the path to find out what it is.
    """
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        return False
    except OSError as exc:
        raise Failure(INPUT_INVALID, f"Cannot read what the changelog path is: {path} ({exc})",
                      changelog=str(path)) from exc
    if not stat.S_ISREG(mode):
        raise Failure(INPUT_INVALID, f"The changelog path is not a regular file: {path}",
                      "CHANGELOG.md is a plain file beside module.json. A symlink, a FIFO or a directory "
                      "in its place is refused, never written through.", changelog=str(path))
    return True


def write(path: Path, text: str) -> None:
    """Write the whole page, or leave the one on disk exactly as it was: a sibling temporary file
    in the same directory, flushed and ``fsync``ed, then one ``os.replace``. A reader sees the old
    page or the new one, never half of either."""
    mode = stat.S_IMODE(path.lstat().st_mode) if _regular(path) else None
    temp = path.parent / f".{path.name}.{os.getpid()}.tmp"
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
    try:
        with os.fdopen(os.open(temp, flags, 0o666), "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        if mode is not None:
            os.chmod(temp, mode)
        os.replace(temp, path)
    except BaseException as exc:
        try:
            temp.unlink()
        except OSError:
            pass
        if isinstance(exc, OSError):
            raise Failure(OPERATION_FAILED, f"Could not write the changelog: {path} ({exc})",
                          "The file on disk was not changed and the temporary file was removed.",
                          changelog=str(path)) from exc
        raise


def differing_lines(existing: str | None, generated: str) -> int:
    """How many lines the file on disk and the generated page disagree on. A missing file
    disagrees on all of them."""
    if existing is None:
        return len(generated.splitlines())
    if existing == generated:
        return 0
    left, right = existing.splitlines(), generated.splitlines()
    opcodes = difflib.SequenceMatcher(a=left, b=right, autojunk=False).get_opcodes()
    return max(sum(max(i2 - i1, j2 - j1) for tag, i1, i2, j1, j2 in opcodes if tag != "equal"), 1)


def _on_disk(path: Path) -> str | None:
    """The page as it is, or None when there is none. A file that is not a regular file is
    refused here as it is on the way in, so a link is never read through either."""
    if not _regular(path):
        return None
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise Failure(INPUT_INVALID, f"The changelog on disk is not readable UTF-8 text: {path} ({exc})",
                      "Delete it and run this route with --write, or fix the file.", changelog=str(path)) from exc


def check(directory) -> dict:
    """Whether the page on disk is the page this renders, byte for byte."""
    directory = Path(directory).expanduser()
    result = render(directory)
    path = directory / FILENAME
    existing = _on_disk(path)
    current = existing == result["text"]
    return {"protocol": PROTOCOL, "module": result["inputs"]["module"], "directory": str(directory),
            "path": str(path), "current": current,
            "diff_lines": 0 if current else differing_lines(existing, result["text"]),
            "exists": existing is not None,
            "versions": result["versions"], "inputs": result["inputs"]}


def run(args) -> dict:
    """The CLI entry: render, and on request write the page or check the one that is there."""
    directory = Path(args.directory).expanduser()
    if args.check:
        report = check(directory)
        if not report["current"]:
            raise Failure(INPUT_INVALID,
                          f"{FILENAME} is {'stale' if report['exists'] else 'missing'} for {report['module']}",
                          f"Run: pat module changelog {args.directory} --write --json. The file is generated "
                          "from the module's git history and evidence.json and is never hand-edited.",
                          report=report, current=False, diff_lines=report["diff_lines"])
        return report
    result = render(directory)
    path = directory / FILENAME
    row = {"protocol": PROTOCOL, "module": result["inputs"]["module"], "directory": str(directory),
           "path": str(path), "written": False, "versions": result["versions"], "inputs": result["inputs"]}
    if not args.write:
        row["text"] = result["text"]
        return row
    before = _on_disk(path)
    write(path, result["text"])
    row["written"] = True
    row["changed"] = before != result["text"]
    row["sha256"] = hashlib.sha256(result["text"].encode("utf-8")).hexdigest()
    row["bytes"] = len(result["text"].encode("utf-8"))
    return row
