"""``knowledge builtin|signature|limits``: generated T6 facts that ship inside the package.

The four JSON files under ``knowledge/`` beside the package are generated by the maintainer from
bytes on disk (the compiled scripts, Unlinker listings and WeaponDefs of the shipped Zombies
zones, and the public knowledge pages) and committed as data; nothing in them is hand-written,
and nothing here reads the network or the game.

- ``builtins.json``: per script VM, every call some shipped Treyarch script makes without any
  script of that VM exporting the name, with the argument counts, receiver and forms seen at the
  call sites; plus the Plutonium client's and installed plugins' extensions from a reviewed seed.
- ``engine-limits.json``: the limits page as rows, each naming the occupancy field that counts
  against it, or ``null`` when nothing on disk does.
- ``occupancy.json``: per map, what the zones the engine loads for it already carry (counts only)
  against each limit.
- ``crash-signatures.json``: the crashes table as regexes with class, cause found and fix that
  worked.

These are inert lookups: no job directory, no receipt beyond the stdout JSON and exit status.
"""
from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

from ..core.errors import INPUT_INVALID, INPUT_LIMIT, INPUT_MISSING, INVALID_ARGUMENTS, Failure

DATA = Path(__file__).resolve().parent.parent / "knowledge"
FILES = ("builtins.json", "engine-limits.json", "crash-signatures.json", "occupancy.json")
VMS = ("server", "client")
NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,63}\Z")
MAP = re.compile(r"^[a-z][a-z0-9_]{1,40}\Z")
TIMESTAMP = re.compile(r"^\[\d{2}:\d{2}:\d{2}\]\s*")
MAX_LOG = 4 * 1024 * 1024
MAX_LINES = 20000
MAX_TEXT = 4096


@lru_cache(maxsize=None)
def load(name: str) -> dict:
    if name not in FILES:
        raise ValueError(f"not a knowledge file: {name}")
    path = DATA / name
    if not path.is_file():
        raise Failure(INPUT_MISSING, f"Knowledge data is missing from this installation: {name}",
                      "The file ships inside the package; reinstall the toolkit.")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or data.get("schema") != 1:
        raise Failure(INPUT_INVALID, f"{name}: unsupported knowledge schema")
    return data


def builtin(name: str, vm: str | None = None) -> dict:
    """Is ``name`` a witnessed native call on a script VM, and with which argument counts."""
    if not isinstance(name, str) or not NAME.match(name):
        raise Failure(INVALID_ARGUMENTS, "A builtin name is letters, digits and underscores (at most 64)",
                      "Example: pat knowledge builtin setanimknob --json")
    if vm is not None and vm not in VMS:
        raise Failure(INVALID_ARGUMENTS, "--vm is server or client")
    data = load("builtins.json")
    key = name.lower()
    rows = {v: data[v][key] for v in VMS if key in data[v] and vm in (None, v)}
    also_on = [v for v in VMS if key in data[v] and v not in rows]
    result = {
        "name": key,
        "vm": vm,
        "verdict": "builtin" if rows else "not-witnessed",
        "rows": rows,
        "also_on": also_on,
        "corpus": {"layers": len(data.get("layers", [])), "scripts": data.get("scripts"), "counts": data.get("counts")},
        "note": "builtin: a shipped Treyarch script calls this name on that VM with these argument counts and no script "
                "exports it; an argument count not listed has no witness. not-witnessed: no shipped script calls it on "
                "that VM; a name a script exports resolves through that script's include, not through the engine. "
                "Rows with origin plutonium or plugin:<name> need that client or DLL.",
    }
    if not rows:
        # A caller branches on the verdict; the note gets skipped. Say the inference limit where it is seen.
        result["caution"] = ("No script shipped in the game's own zones calls this name on that VM. That is absence of "
                             "evidence, not evidence of absence: the engine may still expose it, and a plugin may add it. "
                             "Do not delete or rewrite working code on this answer alone."
                             + (f" It is witnessed on: {', '.join(also_on)}." if also_on else ""))
    return result


def signature(log: Path | None = None, text: str | None = None) -> dict:
    """Match a console log slice (a file, or one line of text) against the crash signatures."""
    if (log is None) == (text is None):
        raise Failure(INVALID_ARGUMENTS, "Give exactly one of --log <file> or --text <line>",
                      "Example: pat knowledge signature --log console_zm.log --json")
    if text is not None:
        if len(text) > MAX_TEXT:
            raise Failure(INPUT_LIMIT, f"--text is at most {MAX_TEXT} characters; pass a file with --log")
        lines = text.splitlines() or [text]
        source = "text"
        truncated = False
    else:
        path = Path(log).expanduser()
        if path.is_symlink() or not path.is_file():
            raise Failure(INPUT_MISSING, f"Log is missing or not a regular file: {path}")
        if path.stat().st_size > MAX_LOG:
            raise Failure(INPUT_LIMIT, f"Log exceeds {MAX_LOG} bytes; copy the slice for the failing load into a smaller file")
        every = path.read_text(encoding="utf-8", errors="replace").splitlines()
        lines = every[-MAX_LINES:]
        truncated = len(every) > len(lines)
        source = str(path)
    rows = load("crash-signatures.json")["rows"]
    compiled = [(re.compile(row["regex"]), row) for row in rows]
    matches = []
    for number, raw in enumerate(lines, 1):
        line = TIMESTAMP.sub("", raw.rstrip())
        for pattern, row in compiled:
            if pattern.search(line):
                matches.append({"line": number, "text": line[:300], "id": row["id"], "class": row["class"],
                                "cause": row["cause"], "fix": row["fix"]})
    classes: dict[str, int] = {}
    for hit in matches:
        classes[hit["class"]] = classes.get(hit["class"], 0) + 1
    return {
        "source": source,
        "lines_read": len(lines),
        "truncated_to_last": MAX_LINES if truncated else None,
        "signatures": len(rows),
        "matches": matches,
        "classes": classes,
        "note": "Line numbers count within the lines read. The cause beside a signature is the one found and fixed once, "
                "not the only possible one; a slice with no match is not a clean load, it is a line nobody has recorded yet. "
                "Diagnosis reads; it does not fix.",
    }


def limits(map_id: str | None = None) -> dict:
    """The observed limits, or one map's loaded zones counted against them."""
    rows = load("engine-limits.json")["rows"]
    occupancy = load("occupancy.json")
    maps = occupancy["maps"]
    if map_id is None:
        return {
            "limits": [{k: row.get(k) for k in ("id", "resource", "bound", "bound_text", "kind", "measured_by", "count_source", "how_to_count")}
                       for row in rows],
            "maps": sorted(maps),
            "zones_not_counted": occupancy.get("zones_not_counted", []),
            "note": "bound is the number observed when a real build hit it, never a specification; count_source names the "
                    "occupancy field that counts against it and null means nothing on disk counts it (record unknown, not passing). "
                    "Pass --map <zm_map> for what that map's loaded zones already carry.",
        }
    if not MAP.match(map_id):
        raise Failure(INVALID_ARGUMENTS, "A map id is lowercase letters, digits and underscores", "Example: --map zm_transit")
    if map_id not in maps:
        raise Failure(INVALID_ARGUMENTS, f"No occupancy is recorded for {map_id}", f"Known maps: {', '.join(sorted(maps))}")
    row = maps[map_id]
    return {"map": map_id, **row, "note": occupancy["note"]}
