#!/usr/bin/env python3
"""Generate docs/BACKENDS.md from the backend pins and the route usage table.

    python tools/backends_doc.py           # print the page
    python tools/backends_doc.py --write   # write docs/BACKENDS.md
    python tools/backends_doc.py --check   # exit 1 if docs/BACKENDS.md is stale

The page names, per program, the upstream project and version, its license, which platforms have
a pinned download, the binaries it provides, and which routes run it with what command line.
Everything comes from ``dev/backends.json``, ``dev/backends.py`` and ``dev/backend_usage.py``;
``tests/test_release_tools.py`` fails when the committed page differs from what this renders.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from plutonium_agent_toolkit.dev import backends  # noqa: E402
from plutonium_agent_toolkit.dev.backend_usage import ADDONS, MANUAL, USAGE  # noqa: E402

PAGE = ROOT / "docs" / "BACKENDS.md"

# Upstream project pages, by backend ID. Release URLs point at an asset; these point at the project.
HOMEPAGES = {
    "oat": "https://github.com/Laupetin/OpenAssetTools",
    "gsc": "https://github.com/xensik/gsc-tool",
    "lua": "https://github.com/JariKCoding/CoDLuaDecompiler",
    "ffmpeg": "https://github.com/BtbN/FFmpeg-Builds",
    "blender": "https://www.blender.org",
    "cast": "https://github.com/dtzxporter/cast",
    "greyhound": "https://github.com/Scobalula/Greyhound",
    "husky": "https://github.com/Scobalula/Husky",
    "c2m": "https://github.com/o-Astral-o/C2Mv3",
}


def _platforms(item: dict) -> str:
    rows = []
    for token in backends.PINNED_PLATFORMS:
        dl = backends.resolve_download(item, token)
        if dl:
            name = Path(urlparse(dl["url"]).path).name
            rows.append(f"{token}: `{name}`")
    if item.get("platform_independent"):
        return "any platform (pure Python): " + ", ".join(r.split(": ", 1)[1] for r in rows[:1])
    return "; ".join(rows) if rows else "none"


def _binaries(item: dict) -> str:
    names = backends.PROGRAM_EXECUTABLES.get(item["id"], [])
    if not names:
        return ", ".join(f"`{p}`" for p in item.get("provides", [])) + " (directory-resolved; no `PAT_BACKEND_` override)"
    return ", ".join(f"`{backends.relative(n, 'windows')}` / `{backends.relative(n, 'linux')}` as `PAT_BACKEND_{n.upper()}`" for n in names)


def _usage_for(item: dict) -> list[dict]:
    names = set(backends.PROGRAM_EXECUTABLES.get(item["id"], []))
    return [u for u in USAGE if u["executable"] in names]


def render() -> str:
    pins = backends.pins()["programs"]
    by_id = {p["id"]: p for p in pins}
    out = []
    out.append("# Backends: which program each route runs\n")
    out.append("<!-- Generated by tools/backends_doc.py from dev/backends.json and dev/backend_usage.py. Do not edit by hand. -->\n")
    out.append("`pat` is a thin wrapper: every development route runs one upstream program as a child process,\n"
               "records its exact command line and log in the job receipt, and checks the result instead of\n"
               "trusting the exit status. This page lists those programs, what the toolkit runs them with, and\n"
               "on which platforms `pat dev setup` has a pinned download. Nothing here is redistributed; each\n"
               "program keeps its own license (see `NOTICE`). Regenerate with `python tools/backends_doc.py --write`.\n")
    out.append("`<...>` is a value the toolkit fills in per job; `[...]` is optional. The `<out>` directory is the\n"
               "job's new `--output`; inputs are staged inside it before the program runs.\n")
    out.append("## Programs the toolkit runs\n")
    for item in pins:
        if item["id"] in MANUAL or item["id"] in ADDONS:
            continue
        out.append(f"### {item['name']}\n")
        out.append(f"- Upstream: <{HOMEPAGES[item['id']]}>")
        out.append(f"- License: {item['license']}")
        out.append(f"- Pinned downloads: {_platforms(item)}")
        out.append(f"- Binaries: {_binaries(item)}")
        if item.get("note"):
            out.append(f"- Note: {item['note']}")
        out.append("")
        uses = _usage_for(item)
        out.append("| Routes | Command line | What the toolkit checks |")
        out.append("| --- | --- | --- |")
        for u in uses:
            routes = ", ".join(f"`{r}`" for r in u["routes"])
            argv = " ".join(u["argv"]).replace("|", "\\|")
            out.append(f"| {routes} | `{argv}` | {u['checks']} |")
        out.append("")
    out.append("## Add-ons loaded by another program\n")
    for pid in ADDONS:
        item = by_id[pid]
        out.append(f"### {item['name']}\n")
        out.append(f"- Upstream: <{HOMEPAGES[pid]}>")
        out.append(f"- License: {item['license']}")
        out.append(f"- Pinned download: {_platforms(item)}")
        out.append(f"- Files: {_binaries(item)}")
        out.append("- Loaded by: Blender, from the backends directory by explicit path (`dev/models.py`); the user's Blender preferences are never touched.")
        out.append("")
    out.append("## Manual GUIs the toolkit only downloads\n")
    out.append("These are pinned so `pat dev setup --only <id>` can fetch and verify them, but no route runs\n"
               "them: their use is manual, through the upstream GUI, on Windows.\n")
    out.append("| Program | Upstream | License | Pinned download | Note |")
    out.append("| --- | --- | --- | --- | --- |")
    for pid in MANUAL:
        item = by_id[pid]
        out.append(f"| {item['name']} | <{HOMEPAGES[pid]}> | {item['license']} | {_platforms(item)} | {item.get('note', '')} |")
    out.append("")
    out.append("## Logos\n")
    out.append("This page uses names and links only. Blender and FFmpeg publish logo policies that allow\n"
               "referential use; the other projects have not been asked. Logos are a later, per-project\n"
               "follow-up after asking each maintainer, and none is included yet.\n")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.write:
        PAGE.write_text(text, encoding="utf-8")
        print(f"wrote {PAGE}")
        return 0
    if args.check:
        current = PAGE.read_text(encoding="utf-8") if PAGE.is_file() else ""
        if current != text:
            print("docs/BACKENDS.md is stale; run: python tools/backends_doc.py --write", file=sys.stderr)
            return 1
        print("docs/BACKENDS.md is current")
        return 0
    print(text, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
