#!/usr/bin/env python3
"""Render docs/TRACK-RECORD.md from docs/track-record.json.

    python tools/track_record_doc.py           # print the page
    python tools/track_record_doc.py --write   # write docs/TRACK-RECORD.md
    python tools/track_record_doc.py --check   # exit 1 if docs/TRACK-RECORD.md is stale

The data file is an export from the authoring workspace's private module registry and reviewed
acceptance records. Edit the data, never the page; ``tests/test_track_record.py`` fails when the
committed page differs from what this renders.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs" / "track-record.json"
PAGE = ROOT / "docs" / "TRACK-RECORD.md"


def cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(d: dict) -> str:
    out = [
        "# Track record: what this approach has built",
        "",
        "This page is generated from `docs/track-record.json`, an export of the authoring workspace's",
        "private module registry and reviewed acceptance records. It describes what a coding agent,",
        "working the way `AGENTS.md`, the knowledge pages and the playbooks describe, has already",
        "produced for Plutonium T6 Zombies. Private receipts back every row; they are not published.",
        "",
        "It is the wide view. [SUPPORT.md](SUPPORT.md) is the narrow one: it grades the packaged `pat`",
        "routes one at a time and is deliberately strict. Read both, and do not tell a user something is",
        "impossible because it has no packaged route; several rows below had none.",
        "",
        f"**{d['totals']['accepted']} of {d['totals']['entries']} cataloged modules are player-accepted.**",
        f"Registry reviewed {d['registry_reviewed_at'][:10]}; milestones reviewed {d['milestones_reviewed_on']}.",
        "",
        f"Counting: {d['counting']}",
        "",
        d["scope_note"],
        "",
        "## The workflow that produced them",
        "",
    ]
    out += [f"{i}. {step}" for i, step in enumerate(d["workflow"], 1)]
    out += [
        "",
        "Step 2 is where the agent does most of its work and where the packaged routes are only part",
        "of the toolbox. Step 4 is a human verdict; the toolkit never records one on its own.",
        "",
        "## Accepted by category",
        "",
        "| Category | Accepted | Entries | Other statuses |",
        "| --- | --- | --- | --- |",
    ]
    for c in d["categories"]:
        other = ", ".join(f"{k} {v}" for k, v in sorted(c["by_status"].items()) if not k.startswith("accepted")) or "none"
        out.append(f"| {cell(c['category'])} | {c['accepted']} | {c['entries']} | {cell(other)} |")
    out += ["", "Status words, as the registry defines them:", ""]
    out += [f"- `{k}`: {v}" for k, v in d["status_definitions"].items()]
    out += ["", "## Representative milestones", "",
            "One row per milestone, with what the agent did to get there and the exact scope of the verdict.", ""]
    for m in d["milestones"]:
        out += [
            f"### {m['title']}",
            "",
            f"Accepted {m['accepted_on']} on {m['base']}, {m['map']}. Category `{m['category']}`.",
            "",
            f"**How:** {m['how']}",
            "",
            f"**Scope of the verdict:** {m['scope']}",
            "",
        ]
        if m.get("quote"):
            out += [f"> {m['quote']}", ""]
    out += [
        "## Beyond the packaged routes",
        "",
        "`pat` packages the routes that have a stable interface and a receipt shape. The agent is not",
        "limited to them. These are workflows the agent completed by reading upstream source, driving a",
        "tool directly, or writing an adapter, and what a fresh agent can start from to repeat them.",
        "",
        "| Workflow | Packaged route | What the agent did | Reproducible from |",
        "| --- | --- | --- | --- |",
    ]
    for c in d["crossings"]:
        out.append(f"| {cell(c['title'])} | {cell(c['packaged_route'])} | {cell(c['what_happened'])} | {cell(c['reproducible_from'])} |")
    out += [
        "",
        "## What this page is not",
        "",
        "It is not a promise that any row works on another base, map or machine, and it is not a route",
        "evidence level. A user's own build earns its own receipts and its own verdict. When the",
        "authoring workspace's registry changes, the data file is re-exported and this page regenerates.",
        "",
        "<!-- Generated by tools/track_record_doc.py; edit docs/track-record.json, never this page. -->",
        "",
    ]
    return "\n".join(out)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    text = render(json.loads(DATA.read_text(encoding="utf-8")))
    if args.write:
        PAGE.write_text(text, encoding="utf-8")
        print(f"wrote {PAGE.relative_to(ROOT)}")
        return 0
    if args.check:
        current = PAGE.read_text(encoding="utf-8") if PAGE.is_file() else ""
        if current != text:
            print("docs/TRACK-RECORD.md is stale; run: python tools/track_record_doc.py --write", file=sys.stderr)
            return 1
        print("docs/TRACK-RECORD.md is current")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
